## Introduction to NumPy

The NumPy array is a data container. It is similar to Python lists,
but it’s specialised for working on numerical data. NumPy is at
the center of scientific Python ecosystem and it is a work-horse
of many scientific libraries including `scikit-learn`, `scikit-image`, `matplotlib`, `scipy` and others.

To use NumPy we need to start python interpreter and import the `numpy` package –
it is customary the use the following `import` statement,
which will make all NumPy functions available under the `np` prefix:

In [4]:
import numpy as np

If NumPy was installed correctly,
this should not produce any messages. Let’s create a simple three-element NumPy array:

In [5]:
x = np.array([2, 1, 5])
x

array([2, 1, 5])

One of the advantages of NumPy is that it allows to apply functions (called ufuncs) to all elements of an array without the need of for loops:

In [6]:
np.sin(x)

array([ 0.90929743,  0.84147098, -0.95892427])

This is not only convenient but also more efficient than iterating through the elements using for loops. Similarly, we can add scalars to all elements or multiply them by a constant:

To construct an array with pre-defined elements we can also use one of the built-in helper functions. `np.arange` works like Python built-in `range`, but it returns an array; `np.ones` and `np.zeros` returns arrays of 0s or 1s; `np.random.rand` creates an array of random number from an interval [0, 1]:

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [9]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
np.random.rand(5)

array([ 0.66702967,  0.19023873,  0.15102339,  0.76372505,  0.29102105])

We can also construct a two- or more dimensional arrays:

In [12]:
x = np.array([[1, 2], [5, 6]])
x


array([[1, 2],
       [5, 6]])

In [13]:
np.ones((2, 2))


array([[ 1.,  1.],
       [ 1.,  1.]])

Alternatively, a n-dimensional array can be obtained by reshaping a 1-D array:

In [14]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Exercise

Create a 5x5 square array with the number 5 on diagonal and zeros otherwise.