# Operations on NumPy arrays

Multiplication of two arrays is elementwise. For example, to calculate a square of each element we may use:

In [2]:
import numpy as np

In [3]:
a = np.arange(3)
b = a * a

In [4]:
a

array([0, 1, 2])

In [5]:
b

array([0, 1, 4])

Matrix products are calculated using the np.dot function:

In [6]:
np.dot(a, a)

5

## Axis-based reductions

With multi-dimensional data, often you want to perform operations on only a specified dimension, or all dimensions. This is true not only for NumPy arrays, but also more advanced data structures based on NumPy.

The np.sum function sums all elements regardless of the number of array dimensions:

In [7]:
b = np.arange(9).reshape(3,3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.sum(b)

36

If you want to sum only columns or rows, you need to pass the index of the axis over which you want to sum:

In [9]:
np.sum(b, 0)


array([ 9, 12, 15])

In [10]:
np.sum(b, 1)

array([ 3, 12, 21])

Other similar reduction functions are `np.min`, `np.max` or `np.mean`. 

In [11]:
a = np.random.rand(3, 3)
print(a)
print(np.argmin(a, 0))

[[ 0.2286213   0.18825905  0.60061028]
 [ 0.60674597  0.86779088  0.49638691]
 [ 0.05274445  0.48968541  0.53257114]]
[2 0 1]


## Sorting

NumPy also implement various sorting algorithms. To sort elements of an array you can use np.sort functions:

In [12]:
a = np.random.rand(4)
a

array([ 0.94750626,  0.35762069,  0.92010044,  0.89958649])

In [13]:
np.sort(a)

array([ 0.35762069,  0.89958649,  0.92010044,  0.94750626])

Similarly to the reduction functions, you can also pass the axis index to sort along:

In [14]:
b = a.reshape(2, 2)
b

array([[ 0.94750626,  0.35762069],
       [ 0.92010044,  0.89958649]])

In [15]:
np.sort(b, 0)

array([[ 0.92010044,  0.35762069],
       [ 0.94750626,  0.89958649]])

In [16]:
np.sort(b, 1)

array([[ 0.35762069,  0.94750626],
       [ 0.89958649,  0.92010044]])

`np.argsort` returns the order of elements in a sorted array:

In [17]:
 np.argsort(a)

array([1, 3, 2, 0])

## Special modules

NumPy also provides extra modules implementing basic numerical methods:


* `np.linalg` – linear algebra,
* `np.fft` – fast Fourier transform,
* `np.random` – random number generators.


## Exercises


**1**. Generate a 10 x 3 array of random numbers (using np.random.rand). From each row, find the column index of the element
closest to 0.75. Make use of np.abs and np.argmin. The result should be a one-dimensional array of integers from 0 to 2.

**2.** Solve the following system of linear equations using np.linalg.solve.
  
  $ 2x + 3 = 3 $
  
  $ 5x − y = 6 $