# Indexing

## Integer indexing and slicing

Individual items of an array can be accessed by the integer index of the element (starting with 0):

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([a[0], a[2], a[-1]])

array([0, 2, 9])

For two- or more dimensional arrays multiple indices should be specified:

In [6]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b[1, 2]

5

Slicing allows to extract sub-arrays of multiple elements from an array. It’s defined by three integers separated by a colon, i.e. `start:end:increment`. Any of the integers can be skipped in which case they are replaced by defaults (0 for `start`, end of array for `end`, and 1 for `increment`):

In [8]:
c = np.arange(9)
c[1:3]

array([1, 2])

In [9]:
c[:3]

array([0, 1, 2])

In [10]:
c[1:]

array([1, 2, 3, 4, 5, 6, 7, 8])

You can also assign elements with slices and indexes:

In [12]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
c[1:8:2] = 1000 

In [16]:
c

array([   0, 1000,    2, 1000,    4, 1000,    6, 1000,    8])

## Exercise


**1.** 

1. Create an array `x` of values from 0 to 11.
2. Create another array as follows:
    `y = x[:4]`
3. Change the first element of `y`, does `x` also change?

**2.** Create an array of zeros and fill it with a checkerboard pattern with of size 8x8:

<img src="img/checkerboard.svg" style="height:300px">

## Boolean indexing

Sometimes we may want to select array elements based on their values. For this case boolean mask is very useful. The mask is an array of the same length as the indexed array containg only `False` or `True` values:

In [41]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [44]:
mask = np.array([False, True, True, False])
a[mask]

array([1, 2])

In most cases the mask is constructed from the values of the array itself. For example:

In [56]:
a = np.array([9, 12, 15, 3])
mask = a > 10
print(mask)

[False  True  True False]


In [57]:
a[mask]

array([12, 15])

In [58]:
odd = (a % 2) == 1
a[odd]

array([ 9, 15,  3])

This could be also done in a single step:

In [59]:
a[(a % 2) == 1]

array([ 9, 15,  3])

Indexing with a mask can be also useful to assign a new value to a sub-array:

In [60]:
a

array([ 9, 12, 15,  3])

In [62]:
a[(a % 2) == 1] = -1
a

array([-1, 12, -1, -1])

## Exercise

**1.** What are the final values of `a` and `b` at the end of the following program? Explain why.

    a = np.arange(5)
    b = a[a < 3]
    b[::2] = 0
     
  1. `a = [0, 1, 2, 3, 4], b = [0, 1, 2]`
  2. `a = [0, 1, 0, 3, 4], b = [0, 1, 0]`
  3. `a = [0, 0, 2, 3, 4], b = [0, 0, 2]`
  4. `a = [0, 1, 2, 3, 4], b = [0, 1, 0]`
  5. `a = [0, 1, 2, 3, 4], b = [0, 1, 0, 3, 0]`


**2.** Write a function called `rectify`, which:

  1. Takes an n-dimensional array as input
  2. Replaces every negative element in this array with zero
  
How could you modify this function to keep the original array intact, and return a *copy* with replaced values?

## Fancy indexing

Indexing can be done with a list/array of integers. In this case the same index can be also repeated several times:

In [81]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
a[[2, 3, 2, 4, 2]] 

array([20, 30, 20, 40, 20])

New values can be also assigned with this kind of indexing:

In [85]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

When a new array is created by indexing with an array of integers, the new array has the same shape than the array of integers. Note that fancing indexing returns a copy and not a view.

In [86]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape

(2, 2)

In [87]:
a[idx]

array([[3, 4],
       [9, 7]])

Fancy indexing is often used to re-order or sort data. You can easily obtain the indices required to sort data using np.argsort:

In [89]:
a = np.random.randint(10, size=5)
a

array([4, 2, 0, 0, 9])

In [91]:
i = np.argsort(a)
a[i]

array([0, 0, 2, 4, 9])

## Copies v/s views

Fancy indexing and boolean indexing return a copy of the elements of the array being indexed (not a view). You can read more about NumPy array indexing here: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In [78]:
a = np.random.rand(10)
print(a)
b = a[[1,2,3,4]]
print(b)
b[:] = 0
print(a)

[ 0.64346065  0.51079959  0.27115952  0.5555193   0.48130741  0.11743986
  0.74197993  0.75001533  0.62505232  0.95159055]
[ 0.51079959  0.27115952  0.5555193   0.48130741]
[ 0.64346065  0.51079959  0.27115952  0.5555193   0.48130741  0.11743986
  0.74197993  0.75001533  0.62505232  0.95159055]


In [79]:
b = a[1:5]
print(b)
b[:] = 0
print(a)

[ 0.51079959  0.27115952  0.5555193   0.48130741]
[ 0.64346065  0.          0.          0.          0.          0.11743986
  0.74197993  0.75001533  0.62505232  0.95159055]


### Assignment *never* copies data

To re-iterate, assignment never copies data. Although we say that boolean/integer indexing returns a copy, it is not the act of assignment that is triggering the copy. The copy is created when we do `a[[1,2,3,4]]`, not when we assign it to `b`.

## Exercise

1. Let `x = np.array([1, 5, 10])`. Which of the following will show `[1, 10]`:
        x[::2]
        x[[1, 3]]
        x[[0, 2]]
        x[0, 2]
        x[[1, -1]]
        x[[False, True, False]]
  
For each statement predict whether it returns a copy or a view.
