# Basic I/O with NumPy

## savetxt and loadtxt

Text-based file formats are preferable, because they can easily be read by humans. When these text files also have "nice" structure, they can also be easily read by computers.

In [31]:
import numpy as np
a = np.array([[1991, 1992, 1993, 1994], [1.1, 1.4, 1.02, 3.9]])

In [32]:
a = a.T
print(a)

[[  1.99100000e+03   1.10000000e+00]
 [  1.99200000e+03   1.40000000e+00]
 [  1.99300000e+03   1.02000000e+00]
 [  1.99400000e+03   3.90000000e+00]]


In [33]:
np.savetxt('GPA.txt', a)

In [34]:
!ls

00-python-intro.ipynb	  03-numpy-indexing.ipynb  GPA.txt    slides.ipynb
01-intro-numpy.ipynb	  04-numpy-io.ipynb	   img
02-numpy-operating.ipynb  data			   README.md


In [35]:
!head GPA.txt

1.991000000000000000e+03 1.100000000000000089e+00
1.992000000000000000e+03 1.399999999999999911e+00
1.993000000000000000e+03 1.020000000000000018e+00
1.994000000000000000e+03 3.899999999999999911e+00


In [36]:
scores = np.loadtxt('GPA.txt')
print(scores)

[[  1.99100000e+03   1.10000000e+00]
 [  1.99200000e+03   1.40000000e+00]
 [  1.99300000e+03   1.02000000e+00]
 [  1.99400000e+03   3.90000000e+00]]


## savez and load

The `savez` and `load` functions help storing and loading several numpy arrays in a special format, `npz`.

In [38]:
locations = np.array([12, 15, 11, 9, 4])
temperatures = np.array([22.1, 21.6, 23.9, 31.3, 33.0])
np.savez('readings.npz', locations=locations, temperatures=temperatures)

In [39]:
!head readings.npz

PK�^jI!Z]xxtemperatures.npy�NUMPYF{'descr': '<f8', 'fortran_order': False, 'shape': (5,), }            
locations.npy�NUMPYF{'descr': '<i8', 'fortran_order': False, 'shape': (5,), }            
���locations.npyPKyI

In [42]:
exp_data = np.load('readings.npz')
print(type(exp_data))
print(exp_data['temperatures'])
print(exp_data['locations'])

<class 'numpy.lib.npyio.NpzFile'>
[ 22.1  21.6  23.9  31.3  33. ]
[12 15 11  9  4]


## Other popular data formats

* **CSV**
  * [built in](https://docs.python.org/3/library/csv.html)
* **HDF5**
  * http://www.pytables.org/
  * http://www.h5py.org/
* **NetCDF**
  * http://unidata.github.io/netcdf4-python/
* **JSON**
  * [built in](https://docs.python.org/3/library/json.html)
* **XML**
  * http://lxml.de/
* **GIS** (e.g. GeoJSON)
  * http://toblerity.org/fiona/